
services:
  pharmacy-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      # Mount instance directory to persist database
      - ./instance:/app/instance
      # Mount source code for development (comment out for production)
      - ./app:/app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: [] 